// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Person {
    // message fields
    pub lname: ::std::string::String,
    pub fname: ::std::string::String,
    pub dob: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Person {
    pub fn new() -> Person {
        ::std::default::Default::default()
    }

    // string lname = 1;

    pub fn clear_lname(&mut self) {
        self.lname.clear();
    }

    // Param is passed by value, moved
    pub fn set_lname(&mut self, v: ::std::string::String) {
        self.lname = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_lname(&mut self) -> &mut ::std::string::String {
        &mut self.lname
    }

    // Take field
    pub fn take_lname(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.lname, ::std::string::String::new())
    }

    pub fn get_lname(&self) -> &str {
        &self.lname
    }

    // string fname = 2;

    pub fn clear_fname(&mut self) {
        self.fname.clear();
    }

    // Param is passed by value, moved
    pub fn set_fname(&mut self, v: ::std::string::String) {
        self.fname = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_fname(&mut self) -> &mut ::std::string::String {
        &mut self.fname
    }

    // Take field
    pub fn take_fname(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.fname, ::std::string::String::new())
    }

    pub fn get_fname(&self) -> &str {
        &self.fname
    }

    // string dob = 3;

    pub fn clear_dob(&mut self) {
        self.dob.clear();
    }

    // Param is passed by value, moved
    pub fn set_dob(&mut self, v: ::std::string::String) {
        self.dob = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dob(&mut self) -> &mut ::std::string::String {
        &mut self.dob
    }

    // Take field
    pub fn take_dob(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dob, ::std::string::String::new())
    }

    pub fn get_dob(&self) -> &str {
        &self.dob
    }
}

impl ::protobuf::Message for Person {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.lname)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.fname)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dob)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.lname.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.lname);
        }
        if !self.fname.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.fname);
        }
        if !self.dob.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.dob);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.lname.is_empty() {
            os.write_string(1, &self.lname)?;
        }
        if !self.fname.is_empty() {
            os.write_string(2, &self.fname)?;
        }
        if !self.dob.is_empty() {
            os.write_string(3, &self.dob)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Person {
        Person::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "lname",
                    |m: &Person| { &m.lname },
                    |m: &mut Person| { &mut m.lname },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "fname",
                    |m: &Person| { &m.fname },
                    |m: &mut Person| { &mut m.fname },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "dob",
                    |m: &Person| { &m.dob },
                    |m: &mut Person| { &mut m.dob },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Person>(
                    "Person",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Person {
        static mut instance: ::protobuf::lazy::Lazy<Person> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Person,
        };
        unsafe {
            instance.get(Person::new)
        }
    }
}

impl ::protobuf::Clear for Person {
    fn clear(&mut self) {
        self.clear_lname();
        self.clear_fname();
        self.clear_dob();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Person {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Person {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18proto/sar_ei_loans.proto\"F\n\x06Person\x12\x14\n\x05lname\x18\x01\
    \x20\x01(\tR\x05lname\x12\x14\n\x05fname\x18\x02\x20\x01(\tR\x05fname\
    \x12\x10\n\x03dob\x18\x03\x20\x01(\tR\x03dobb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
